const {
  DEFAULT_EXECUTION_POLICY,
  FAILURE_NODE_STATUSES,
  INCOMPLETE_FOR_DONE_STATUSES,
  SOFT_DEP_SATISFIED_STATUSES,
  SUCCESS_NODE_STATUSES,
  TERMINAL_NODE_STATUSES
} = require("./constants");
function isTerminalStatus(status) {
  return TERMINAL_NODE_STATUSES.includes(status);
}
function isIncompleteStatus(status) {
  return INCOMPLETE_FOR_DONE_STATUSES.includes(status);
}
module.exports = {
  DEFAULT_EXECUTION_POLICY,
  TERMINAL_NODE_STATUSES,
  SUCCESS_NODE_STATUSES,
  FAILURE_NODE_STATUSES,
  SOFT_DEP_SATISFIED_STATUSES,
  INCOMPLETE_FOR_DONE_STATUSES,
  isTerminalStatus,
  isIncompleteStatus
};
