import { NextResponse } from "next/server";
import {
  upsertGithubPr,
  upsertPrLink,
} from "@/lib/github-pr-store";
import { upsertGithubRepo } from "@/lib/github-repo-store";
import type { GithubPr } from "@/lib/github-types";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

export async function POST() {
  if (process.env.NODE_ENV === "production") {
    return NextResponse.json(
      { ok: false, error: "forbidden_in_production" },
      { status: 403 },
    );
  }

  const now = Date.now();
  const hour = 60 * 60 * 1000;

  const repos = [
    { owner: "agx-org", name: "agx", defaultBranch: "main", private: false },
    {
      owner: "agx-org",
      name: "agx-web",
      defaultBranch: "main",
      private: false,
    },
    { owner: "demo", name: "other", defaultBranch: "main", private: true },
  ];
  for (const r of repos) upsertGithubRepo(r);

  const prs: GithubPr[] = [
    {
      id: "agx-org/agx#101",
      repoId: "agx-org/agx",
      number: 101,
      title: "AGX-12 Add PRs skeleton page",
      body: "Implements the /prs skeleton with a quick-filter tabs UI.\n\nRelates to AGX-12.",
      state: "open",
      draft: false,
      authorLogin: "mendrika",
      headRef: "agx-12/prs-skeleton",
      headSha: "abc1234",
      baseRef: "main",
      url: "https://github.com/agx-org/agx/pull/101",
      ciStatus: "success",
      reviewDecision: "review_required",
      assignees: ["mendrika"],
      reviewers: [{ login: "alice", state: "pending" }],
      labels: ["feature"],
      createdAt: now - 6 * hour,
      updatedAt: now - 1 * hour,
      mergedAt: null,
      closedAt: null,
      lastSyncedAt: now,
    },
    {
      id: "agx-org/agx#102",
      repoId: "agx-org/agx",
      number: 102,
      title: "Fix tracker drag race",
      body: "Patches a race condition when dragging tickets.",
      state: "open",
      draft: true,
      authorLogin: "alice",
      headRef: "fix/tracker-race",
      headSha: "def5678",
      baseRef: "main",
      url: "https://github.com/agx-org/agx/pull/102",
      ciStatus: "pending",
      reviewDecision: null,
      assignees: [],
      reviewers: [{ login: "mendrika", state: "pending" }],
      labels: ["bug"],
      createdAt: now - 4 * hour,
      updatedAt: now - 30 * 60 * 1000,
      mergedAt: null,
      closedAt: null,
      lastSyncedAt: now,
    },
    {
      id: "agx-org/agx#100",
      repoId: "agx-org/agx",
      number: 100,
      title: "AGX-9 multi-tracker objectives",
      body: "Already merged.",
      state: "merged",
      draft: false,
      authorLogin: "mendrika",
      headRef: "agx-9/multi-tracker",
      headSha: "aaa0001",
      baseRef: "main",
      url: "https://github.com/agx-org/agx/pull/100",
      ciStatus: "success",
      reviewDecision: "approved",
      assignees: ["mendrika"],
      reviewers: [{ login: "alice", state: "approved" }],
      labels: ["feature"],
      createdAt: now - 48 * hour,
      updatedAt: now - 24 * hour,
      mergedAt: now - 24 * hour,
      closedAt: now - 24 * hour,
      lastSyncedAt: now,
    },
    {
      id: "agx-org/agx-web#7",
      repoId: "agx-org/agx-web",
      number: 7,
      title: "AGX-4 landing page SEO tags",
      body: "Adds JSON-LD and OG tags.",
      state: "open",
      draft: false,
      authorLogin: "bob",
      headRef: "agx-4/seo",
      headSha: "bbb0007",
      baseRef: "main",
      url: "https://github.com/agx-org/agx-web/pull/7",
      ciStatus: "failure",
      reviewDecision: "changes_requested",
      assignees: ["bob"],
      reviewers: [
        { login: "mendrika", state: "pending" },
        { login: "alice", state: "changes_requested" },
      ],
      labels: ["seo"],
      createdAt: now - 12 * hour,
      updatedAt: now - 2 * hour,
      mergedAt: null,
      closedAt: null,
      lastSyncedAt: now,
    },
    {
      id: "agx-org/agx-web#8",
      repoId: "agx-org/agx-web",
      number: 8,
      title: "Bump next to 15.2",
      body: "Dependency bump.",
      state: "closed",
      draft: false,
      authorLogin: "dependabot",
      headRef: "deps/next-15.2",
      headSha: "ccc0008",
      baseRef: "main",
      url: "https://github.com/agx-org/agx-web/pull/8",
      ciStatus: "failure",
      reviewDecision: null,
      assignees: [],
      reviewers: [],
      labels: ["dependencies"],
      createdAt: now - 30 * hour,
      updatedAt: now - 20 * hour,
      mergedAt: null,
      closedAt: now - 20 * hour,
      lastSyncedAt: now,
    },
    {
      id: "agx-org/agx-web#9",
      repoId: "agx-org/agx-web",
      number: 9,
      title: "Tweak hero copy",
      body: "Minor copy change.",
      state: "open",
      draft: false,
      authorLogin: "mendrika",
      headRef: "copy/hero",
      headSha: "ddd0009",
      baseRef: "main",
      url: "https://github.com/agx-org/agx-web/pull/9",
      ciStatus: "success",
      reviewDecision: "review_required",
      assignees: [],
      reviewers: [{ login: "bob", state: "pending" }],
      labels: [],
      createdAt: now - 3 * hour,
      updatedAt: now - 10 * 60 * 1000,
      mergedAt: null,
      closedAt: null,
      lastSyncedAt: now,
    },
    {
      id: "demo/other#1",
      repoId: "demo/other",
      number: 1,
      title: "Experimental: try new router",
      body: "Unrelated demo repo PR.",
      state: "open",
      draft: true,
      authorLogin: "carol",
      headRef: "exp/router",
      headSha: "eee0001",
      baseRef: "main",
      url: "https://github.com/demo/other/pull/1",
      ciStatus: null,
      reviewDecision: null,
      assignees: ["carol"],
      reviewers: [],
      labels: ["experiment"],
      createdAt: now - 8 * hour,
      updatedAt: now - 5 * hour,
      mergedAt: null,
      closedAt: null,
      lastSyncedAt: now,
    },
    {
      id: "demo/other#2",
      repoId: "demo/other",
      number: 2,
      title: "AGX-7 add telemetry opt-out",
      body: "Per AGX-7, add a CLI flag to disable telemetry.",
      state: "merged",
      draft: false,
      authorLogin: "carol",
      headRef: "agx-7/telemetry-opt-out",
      headSha: "fff0002",
      baseRef: "main",
      url: "https://github.com/demo/other/pull/2",
      ciStatus: "success",
      reviewDecision: "approved",
      assignees: ["carol"],
      reviewers: [{ login: "mendrika", state: "approved" }],
      labels: [],
      createdAt: now - 72 * hour,
      updatedAt: now - 48 * hour,
      mergedAt: now - 48 * hour,
      closedAt: now - 48 * hour,
      lastSyncedAt: now,
    },
  ];
  for (const pr of prs) upsertGithubPr(pr);

  const links = [
    {
      prId: "agx-org/agx#101",
      targetType: "agx_task" as const,
      targetId: "AGX-12",
      linkSource: "branch" as const,
    },
    {
      prId: "demo/other#2",
      targetType: "agx_task" as const,
      targetId: "AGX-7",
      linkSource: "manual" as const,
    },
  ];
  for (const l of links) upsertPrLink(l);

  return NextResponse.json({
    ok: true,
    counts: { repos: repos.length, prs: prs.length, links: links.length },
  });
}
